# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lock.interface <- function(pathIn, exclusive) {
    .Call('flock_lockInterface', PACKAGE = 'flock', pathIn, exclusive)
}

unlock.interface <- function(descriptorIn) {
    invisible(.Call('flock_unlockInterface', PACKAGE = 'flock', descriptorIn))
}

